### ISSUE TITLE
Vulnerabilities on version 3.0.1.7

### ISSUE THREAD

**Issue by nj8** [colosa/processmaker#2556]
Hi, I've found some vulnerabilities on the version 3.0.1.7 of ProcessMaker. This is a brief description of these four vulnerabilities.

Details of these vulnerabilities have been sent to development team in a private way because the corrected version is not yet published. For this reason, detailled PoC isn't published in this github discussion.

Please note that all of these vulnerabilities are exploitable through auto-submit HTML form and/or basics phishing technics that will lead authenticated users to click on pre-forged link and finally execute XSS/CSRF vulnerabilities.
## CSRF on Designer Project Creation

Designer Project creation process is vulnerable to CSRF vulnerability. a forged request can be used to force an authenticated user with designer project creation rights to create a new Designer project. 
Note that this CSRF vulnerability can be combined with another vulnerability that expose a stored XSS vulnerability in the Description input of Designer Project.
## CSRF on group creation

Group creation process is vulnerable to CSRF vulnerability, a forged request can be used to force an authenticated user with admin rights to create a new group.
## Stored XSS on Designer Project Creation

The "description" input of the designer project creation process is vulnerable to stored XSS. A user can use this input to store an XSS an make other user's browsers executes controlled JavaScript instructions.
## Reflected Cross-Site Scripting (RXSS) with authentication

The search form in the Design Project can redirect user to a blank page without HTML code. This page display some information including user request. We can use this situation to execute JavaScript instruction into browser's user.
Note that a search request use POST transmission method, to exploit this vulnerability, an attacker need to trap a user to visit a HTML form with auto-submit Javascript tricks to generate the forged request.

A public advisory will be released when the corrected version will be available.

**Comment by ITSec-ProcessMaker** [comment]
Hello and thank you for the report.
Regarding your findings:

**1.** CSRF on Designer Project Creation
**2.** CSRF on group creation

Both issues will be fixed on ProcessMaker version 4.0 (Release: Q4/2017). 
We consider these vulnerabilities to be low priority as their impact is very low.
They only real damage these vulnerabilities could have is in combination with the XSS vulnerabilities.

**3.** Stored XSS on Designer Project Creation
**4.** Reflected Cross-Site Scripting (RXSS) with authentication

These vulnerabilities will be fixed on ProcessMaker version 3.0.1.8 (Release:April 26/2016) as we consider these to be high priority.

Stored XSS on Designer Project Creation vulnerability has Jira ticket HOR-285 assigned to it
Reflected Cross-Site Scripting (RXSS) with authentication has Jira ticket HOR-286 assigned to it

**Comment by nj8** [comment]
Thanks for your feedback ! :)

I'm willing to test your correction if needed.

Regards,

**Comment by ITSec-ProcessMaker** [comment]
Hello,

We are proud to announce ProcessMaker version 3.0.1.8, improving on our ProcessMaker 3.0.1.7 platform, which we released in January.

This new release includes the following security improvements:

**New PMFunctions**, New PMFunctions have been created in order to reduce the code needed to access ProcessMaker data; and to avoid direct access to the ProcessMaker tables, using the executeQuery() function. Take a look at the complete [PM Functions list](http://wiki.processmaker.com/3.0/ProcessMaker_Functions) for this version.

**executeQuery Improvement**, This function has been modified to include a blacklist of ProcessMaker tables. Meaning that we are restricting the modification of ProcessMaker core tables, using the executeQuery function. The goal of this restriction is to guarantee data integrity in ProcessMaker Core Tables. Many known issues were related to data integrity problems in ProcessMaker, caused by direct modification of core tables using SQL queries. Usual queries executed against ProcessMaker core tables were implemented in PMFunctions. Additionally, this restriction forces Process Architects to create "Migration ready" processes, taking into account that the PM Functions used won’t have to be modified, even if the ProcessMaker data schema changes in future versions. For more information, see: [Protecting Processmaker Core Tables and PM Tables](http://wiki.processmaker.com/3.0/Consulting_the_ProcessMaker_databases#Protecting_PM_Core_Tables).

**Blocking Multiple browser instances**, A new setting is available to forbid opening multiple browser instances of ProcessMaker. This restriction affects the following tabs: Home, Designer, Dashboards, KPIs, Admin, and any of the options inside them. For more information, visit: [Blocking multiple browser instances](http://wiki.processmaker.com/3.0/Configuration_File_env.ini#Blocking_multiple_browser_instances).

**Vulnerabilities fixes**, This version includes many security improvements and corrections, including the findings you reported (HOR-285, HOR-286):

**HOR-878**. High Code Injection bootstrap.php
**HOR-877**. OS Command Injection Package.php
**HOR-844**. Information Leakage
**HOR-838**. OS Command Injection
**HOR-835**. Directory Traversal
**HOR-553**. Improve executeQuery function - log errors / restricted executions
**HOR-393**. Change the functionality: open a new tab in IE 11 for security reasons
**HOR-368**. Security Avoid the problem of overwriting session data opening multiple browser tabs or multiple browser instances
**HOR-286**. Security Issue - Reflected Cross-Site Scripting (RXSS) with authentication
**HOR-285**. Security Issue - Stored XSS on Designer Project Creation
**HOR-284**. Security Issue - Harcoded credentials
**HOR-283**. Security Issue - Password brute-forcing is possible
**HOR-282**. Security Issue - Multiple Cross Site Scripting Issues
**HOR-281**. Security Issue - Unauthenticated SQL Injection - GET /gulliver/genericAjax
**HOR-280**. Security Issue - SQL Injections - 
POST /sysworkflow/en/neoclassic/cases/proxyProcessList.php
**HOR-279**. Security Issue - SQL Injections - 
POST /sysworkflow/en/neoclassic/cases/proxyPMTablesSaveFields.php
**HOR-278**. Security Issue - SQL Injections - 
GET /sysworkflow/en/neoclassic/events/eventsAjax
**HOR-245**. Security issue: Possibility of SQL Injection when forms are submitted 
**HOR-244**. executeQuery improvement

Please contact me if you need more information.

With my best regards,

**Comment by tdondich** [comment]
We are closing this issue due to lack of response from original requester.  Please review most recent releases for security related fixes.
